name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: wellingtonolive
          outputs: assets/github-contribution-grid-snake.svg

      - name: Commit snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"